assets:
  - db.sql.gz
steps:
  - name: Upgrade to php 5.6
    plugin: Script
    script: |
      apt-get update
      apt-get install -y software-properties-common language-pack-en-base
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/apache2
      apt-get update
      apt-get install -y php5.6 php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml php5.6-gd php5.6-curl php5.6-json php5.6-imagick php5.6-dev php5.6-gmp
      a2dismod php5
      a2dismod php7.1
      a2enmod php5.6
      apachectl graceful
      php -v
  - name: Composer Install
    plugin: Shell
    command: |
      cd $SRC_DIR
      composer self-update
      composer install --prefer-dist -o
  - name: Import start DB
    plugin: Drupal
    database: db.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    subDirectory: docroot
    drupalVersion: 8
  - name: Import Config
    plugin: Script
    script:
      - cd $SRC_DIR/docroot
      - drush cim dev -y
  - name: Run update and clear cache
    plugin: Script
    script:
      - cd $SRC_DIR/docroot
      - drush entup -y
      - drush up -y
      - drush cr
