assets:
  - db.sql.gz
steps:
  - name: Upgrade to php 5.6
    plugin: Script
    script:
      - apt-get update
      - apt-get install software-properties-common -y
      - add-apt-repository ppa:ondrej/php5-5.6
      - sudo apt-get install php5
      - php -v
  - name: Composer Install
    plugin: Shell
    command: 'cd $SRC_DIR; composer self-update 1.2.2; composer install --prefer-dist -o'
  - name: Import start DB
    plugin: Drupal
    database: db.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    subDirectory: docroot
    drupalVersion: 8
  - name: Import Config
    plugin: Script
    script:
      - cd $SRC_DIR/docroot
      - drush cim dev -y
  - name: Run update and clear cache
    plugin: Script
    script:
      - cd $SRC_DIR/docroot
      - drush entup -y
      - drush up -y
      - drush cr
