assets:
  - db.sql.gz
steps:
  - name: Update PHP
    plugin: Shell
    command: |
      apt-get update
      apt-get install -y software-properties-common language-pack-en-base
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/apache2
      apt-get update
      apt-get -y install php5.6 php5.6-cli php5.6-common php5.6-curl php5.6-dev php5.6-gd php5.6-intl php5.6-json php5.6-ldap php5.6-mbstring php5.6-mcrypt php5.6-memcache php5.6-memcached php5.6-mysql php5.6-pgsql php5.6-readline php5.6-sqlite php5.6-xml php5.6-xsl libzip4 php5.6-zip
      a2dismod php5
      a2enmod php5.6
      apachectl graceful
      php -v
  - name: Composer Install
    plugin: Shell
    command: |
      cd $SRC_DIR
      composer self-update 1.2.2
      composer --version
      composer install --prefer-dist -o
  - name: Import start DB
    plugin: Drupal
    database: db.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    subDirectory: docroot
    drupalVersion: 8
  - name: Import Config
    plugin: Script
    script:
      - cd $SRC_DIR/docroot
      - drush cim dev -y
  - name: Run update and clear cache
    plugin: Script
    script:
      - cd $SRC_DIR/docroot
      - drush entup -y
      - drush up -y
      - drush cr
